### ISSUE TITLE
Got `UnicodeDecodeError` during installation.

### ISSUE THREAD

**Issue by figkim** [mlshapiro/jupyterlab-flake8#31]
Hi. I got an error when I tried to install `jupyterlab-flake8`. 
Here is detailed log for the error message.

```
Yarn configuration loaded.
Node v10.13.0

> /home/ehgud5/miniconda3/envs/mv/bin/npm pack jupyterlab-flake8
Traceback (most recent call last):

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/commands.py", line 398, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/commands.py", line 611, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/commands.py", line 1507, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/commands.py", line 1574, in _extract_package
    ret = self._run([which('npm'), 'pack', source], cwd=tempdir)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/commands.py", line 1748, in _run
    return proc.wait()

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/site-packages/jupyterlab/commands.py", line 107, in wait
    out, _ = proc.communicate(timeout=.1)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/subprocess.py", line 1574, in _communicate
    self.stdout.errors)

  File "/home/ehgud5/miniconda3/envs/mv/lib/python3.6/subprocess.py", line 760, in _translate_newlines
    data = data.decode(encoding, errors)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 23: ordinal not in range(128)

Exiting application: jupyter
```

**Comment by mlshapiro** [comment]
This is likely due to your terminal encoding. See:

- https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal/49127686#49127686
- https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte
